config/routes.rb
Rails.application.routes.draw do
  root 'customers#index'

  resources :cards
  resources :customers
  resources :plans
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/card.rb
class Card < ApplicationRecord
  belongs_to :customer

  def to_s
    "Ending with #{self.last_4} - #{self.exp_month}/#{self.exp_year}"
  end
end

app/models/customer.rb
class Customer < ApplicationRecord
  require "stripe"

  attr_accessor :card_number, :cvc, :exp_month, :exp_year

  validates :first_name, :last_name, :email, presence: true

  belongs_to :plan
  has_many :cards

  before_save :create_customer_in_stripe

  def create_customer_in_stripe
    begin
      token = Stripe::Token.create(
                  :card => {
                    :number => self.card_number,
                    :exp_month => self.exp_month,
                    :exp_year => self.exp_year,
                    :cvc => self.cvc
                  },
                )

      customer = Stripe::Customer.create(
        :description => "Customer for #{self.email}",
        :source => token[:id]
      )

      customer[:sources][:data].each do |card|
        customer_card = self.cards.new(stripe_card_id: card[:id], last_4: card[:last4], brand: card[:brand], exp_month: card[:exp_month], exp_year: card[:exp_year])
        customer_card.default_card = true if self.cards.count == 0        
      end

      self.stripe_customer_id = customer[:id]

      subscription = Stripe::Subscription.create(
        :customer => self.stripe_customer_id,
        :items => [
          {
            :plan => self.plan.stripe_plan_id,
          },
        ]
      )

    rescue => e
      errors.add(:base, e)
      throw(:abort)
    end
  end

  def to_s
    self.first_name + " " + self.last_name
  end
end

app/models/plan.rb
class Plan < ApplicationRecord
  has_many :customers
  
  require "stripe"

  validates :name, :amount, :interval, presence: true

  before_save :create_plan_in_stripe

  def create_plan_in_stripe
    begin
      plan = Stripe::Plan.create(
        :amount => (self.amount.to_f * 100).to_i,
        :interval => self.interval,
        :name => self.name,
        :currency => "usd",
        :id => self.desired_plan_id
      )

      self.stripe_plan_id = plan[:id]
    rescue => e
      body = e.json_body
      err  = body[:error]
      errors.add(:base, err)
      throw(:abort)
    end
  end

  def to_s
    self.name
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/cards_controller.rb
class CardsController < ApplicationController
  before_action :set_card, only: [:show, :edit, :update, :destroy]

  # GET /cards
  # GET /cards.json
  def index
    @cards = Card.all
  end

  # GET /cards/1
  # GET /cards/1.json
  def show
  end

  # GET /cards/new
  def new
    @card = Card.new
  end

  # GET /cards/1/edit
  def edit
  end

  # POST /cards
  # POST /cards.json
  def create
    @card = Card.new(card_params)

    respond_to do |format|
      if @card.save
        format.html { redirect_to @card, notice: 'Card was successfully created.' }
        format.json { render :show, status: :created, location: @card }
      else
        format.html { render :new }
        format.json { render json: @card.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /cards/1
  # PATCH/PUT /cards/1.json
  def update
    respond_to do |format|
      if @card.update(card_params)
        format.html { redirect_to @card, notice: 'Card was successfully updated.' }
        format.json { render :show, status: :ok, location: @card }
      else
        format.html { render :edit }
        format.json { render json: @card.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /cards/1
  # DELETE /cards/1.json
  def destroy
    @card.destroy
    respond_to do |format|
      format.html { redirect_to cards_url, notice: 'Card was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_card
      @card = Card.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def card_params
      params.require(:card).permit(:customer_id, :stripe_card_id, :default_card, :last_4, :brand, :exp_month, :exp_year)
    end
end

app/controllers/customers_controller.rb
class CustomersController < ApplicationController
  before_action :set_customer, only: [:show, :edit, :update, :destroy]

  # GET /customers
  # GET /customers.json
  def index
    @customers = Customer.all
  end

  # GET /customers/1
  # GET /customers/1.json
  def show
  end

  # GET /customers/new
  def new
    @customer = Customer.new
  end

  # GET /customers/1/edit
  def edit
  end

  # POST /customers
  # POST /customers.json
  def create
    @customer = Customer.new(customer_params)

    respond_to do |format|
      if @customer.save
        format.html { redirect_to @customer, notice: 'Customer was successfully created.' }
        format.json { render :show, status: :created, location: @customer }
      else
        format.html { render :new }
        format.json { render json: @customer.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /customers/1
  # PATCH/PUT /customers/1.json
  def update
    respond_to do |format|
      if @customer.update(customer_params)
        format.html { redirect_to @customer, notice: 'Customer was successfully updated.' }
        format.json { render :show, status: :ok, location: @customer }
      else
        format.html { render :edit }
        format.json { render json: @customer.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /customers/1
  # DELETE /customers/1.json
  def destroy
    @customer.destroy
    respond_to do |format|
      format.html { redirect_to customers_url, notice: 'Customer was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_customer
      @customer = Customer.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def customer_params
      params.require(:customer).permit(:first_name, :last_name, :email, :plan_id, :card_number, :cvc, :exp_month, :exp_year)
    end
end

app/controllers/plans_controller.rb
class PlansController < ApplicationController
  before_action :set_plan, only: [:show, :edit, :update, :destroy]

  # GET /plans
  # GET /plans.json
  def index
    @plans = Plan.all
  end

  # GET /plans/1
  # GET /plans/1.json
  def show
  end

  # GET /plans/new
  def new
    @plan = Plan.new
  end

  # GET /plans/1/edit
  def edit
  end

  # POST /plans
  # POST /plans.json
  def create
    @plan = Plan.new(plan_params)

    respond_to do |format|
      if @plan.save
        format.html { redirect_to @plan, notice: 'Plan was successfully created.' }
        format.json { render :show, status: :created, location: @plan }
      else
        format.html { render :new }
        format.json { render json: @plan.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /plans/1
  # PATCH/PUT /plans/1.json
  def update
    respond_to do |format|
      if @plan.update(plan_params)
        format.html { redirect_to @plan, notice: 'Plan was successfully updated.' }
        format.json { render :show, status: :ok, location: @plan }
      else
        format.html { render :edit }
        format.json { render json: @plan.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /plans/1
  # DELETE /plans/1.json
  def destroy
    @plan.destroy
    respond_to do |format|
      format.html { redirect_to plans_url, notice: 'Plan was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_plan
      @plan = Plan.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def plan_params
      params.require(:plan).permit(:name, :amount, :interval, :desired_plan_id)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cards_helper.rb
module CardsHelper
end

app/helpers/customers_helper.rb
module CustomersHelper
end

app/helpers/plans_helper.rb
module PlansHelper
end

app/views/cards/_form.html.erb
<%= form_with(model: card, local: true) do |form| %>
  <% if card.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(card.errors.count, "error") %> prohibited this card from being saved:</h2>

      <ul>
      <% card.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :customer_id %>
    <%= form.text_field :customer_id, id: :card_customer_id %>
  </div>

  <div class="field">
    <%= form.label :stripe_card_id %>
    <%= form.text_field :stripe_card_id, id: :card_stripe_card_id %>
  </div>

  <div class="field">
    <%= form.label :default_card %>
    <%= form.text_field :default_card, id: :card_default_card %>
  </div>

  <div class="field">
    <%= form.label :last_4 %>
    <%= form.text_field :last_4, id: :card_last_4 %>
  </div>

  <div class="field">
    <%= form.label :brand %>
    <%= form.text_field :brand, id: :card_brand %>
  </div>

  <div class="field">
    <%= form.label :exp_month %>
    <%= form.text_field :exp_month, id: :card_exp_month %>
  </div>

  <div class="field">
    <%= form.label :exp_year %>
    <%= form.text_field :exp_year, id: :card_exp_year %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/cards/edit.html.erb
<h1>Editing Card</h1>

<%= render 'form', card: @card %>

<%= link_to 'Show', @card %> |
<%= link_to 'Back', cards_path %>

app/views/cards/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Cards</h1>

<table>
  <thead>
    <tr>
      <th>Customer</th>
      <th>Stripe card</th>
      <th>default_card</th>
      <th>Last 4</th>
      <th>Brand</th>
      <th>Exp month</th>
      <th>Exp year</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @cards.each do |card| %>
      <tr>
        <td><%= card.customer %></td>
        <td><%= card.stripe_card_id %></td>
        <td><%= card.default_card %></td>
        <td><%= card.last_4 %></td>
        <td><%= card.brand %></td>
        <td><%= card.exp_month %></td>
        <td><%= card.exp_year %></td>
        <td><%= link_to 'Show', card %></td>
        <td><%= link_to 'Edit', edit_card_path(card) %></td>
        <td><%= link_to 'Destroy', card, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Card', new_card_path %>

app/views/cards/new.html.erb
<h1>New Card</h1>

<%= render 'form', card: @card %>

<%= link_to 'Back', cards_path %>

app/views/cards/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Customer:</strong>
  <%= @card.customer %>
</p>

<p>
  <strong>Stripe card:</strong>
  <%= @card.stripe_card_id %>
</p>

<p>
  <strong>default_card:</strong>
  <%= @card.default_card %>
</p>

<p>
  <strong>Last 4:</strong>
  <%= @card.last_4 %>
</p>

<p>
  <strong>Brand:</strong>
  <%= @card.brand %>
</p>

<p>
  <strong>Exp month:</strong>
  <%= @card.exp_month %>
</p>

<p>
  <strong>Exp year:</strong>
  <%= @card.exp_year %>
</p>

<%= link_to 'Edit', edit_card_path(@card) %> |
<%= link_to 'Back', cards_path %>

app/views/customers/_form.html.erb
<%= form_with(model: customer, local: true) do |form| %>
  <% if customer.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(customer.errors.count, "error") %> prohibited this customer from being saved:</h2>

      <ul>
      <% customer.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :first_name %>
    <%= form.text_field :first_name, id: :customer_first_name %>
  </div>

  <div class="field">
    <%= form.label :last_name %>
    <%= form.text_field :last_name, id: :customer_last_name %>
  </div>

  <div class="field">
    <%= form.label :email %>
    <%= form.text_field :email, id: :customer_email %>
  </div>

  <div class="field">
    <%= form.label :plan_id %>
    <%= form.collection_select :plan_id, Plan.all, :id, :name, {}, {} %>
  </div>

  <% if @customer.new? %>
    <div class="field">
      <%= form.label :card_number %>
      <%= form.text_field :card_number %>
    </div>

    <div class="field">
      <%= form.label :cvc %>
      <%= form.text_field :cvc %>
    </div>

    <div class="field">
      <%= form.label :exp_month %>
      <%= form.text_field :exp_month %>
    </div>

    <div class="field">
      <%= form.label :exp_year %>
      <%= form.text_field :exp_year %>
    </div>
  <% end %>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/customers/edit.html.erb
<h1>Editing Customer</h1>

<%= render 'form', customer: @customer %>

<%= link_to 'Show', @customer %> |
<%= link_to 'Back', customers_path %>

app/views/customers/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Customers</h1>

<table>
  <thead>
    <tr>
      <th>First name</th>
      <th>Last name</th>
      <th>Email</th>
      <th>Plan</th>
      <th>Stripe customer</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @customers.each do |customer| %>
      <tr>
        <td><%= customer.first_name %></td>
        <td><%= customer.last_name %></td>
        <td><%= customer.email %></td>
        <td><%= customer.plan %></td>
        <td><%= customer.stripe_customer_id %></td>
        <td><%= link_to 'Show', customer %></td>
        <td><%= link_to 'Edit', edit_customer_path(customer) %></td>
        <td><%= link_to 'Destroy', customer, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Customer', new_customer_path %>

app/views/customers/new.html.erb
<h1>New Customer</h1>

<%= render 'form', customer: @customer %>

<%= link_to 'Back', customers_path %>

app/views/customers/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>First name:</strong>
  <%= @customer.first_name %>
</p>

<p>
  <strong>Last name:</strong>
  <%= @customer.last_name %>
</p>

<p>
  <strong>Email:</strong>
  <%= @customer.email %>
</p>

<p>
  <strong>Plan:</strong>
  <%= @customer.plan %>
</p>

<p>
  <strong>Stripe customer:</strong>
  <%= @customer.stripe_customer_id %>
</p>

<b>Card Details</b>
<ul>
  <% @customer.cards.each do |card| %>
    <div class="field">
      <li><%= card.to_s %></li>
    </div>
  <% end %>
</ul>
<%= link_to 'Edit', edit_customer_path(@customer) %> |
<%= link_to 'Back', customers_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>StripeDemo</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= link_to "Customers", customers_path %> |
    <%= link_to "Plans", plans_path %> |
    <%= link_to "Cards", cards_path %>
    <hr>
    <%= yield %>
  </body>
</html>

app/views/plans/_form.html.erb
<%= form_with(model: plan, local: true) do |form| %>
  <% if plan.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(plan.errors.count, "error") %> prohibited this plan from being saved:</h2>

      <ul>
      <% plan.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name, id: :plan_name %>
  </div>

  <div class="field">
    <%= form.label :amount %>
    <%= form.text_field :amount, id: :plan_amount %>
  </div>

  <div class="field">
    <%= form.label :interval %>
    <%= form.text_field :interval, id: :plan_interval %>
  </div>

  <div class="field">
    <%= form.label :desired_plan_id %>
    <%= form.text_field :desired_plan_id, id: :plan_desired_plan_id %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/plans/edit.html.erb
<h1>Editing Plan</h1>

<%= render 'form', plan: @plan %>

<%= link_to 'Show', @plan %> |
<%= link_to 'Back', plans_path %>

app/views/plans/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Plans</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Amount</th>
      <th>Interval</th>
      <th>Desired plan</th>
      <th>Stripe plan</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @plans.each do |plan| %>
      <tr>
        <td><%= plan.name %></td>
        <td><%= plan.amount %></td>
        <td><%= plan.interval %></td>
        <td><%= plan.desired_plan_id %></td>
        <td><%= plan.stripe_plan_id %></td>
        <td><%= link_to 'Show', plan %></td>
        <td><%= link_to 'Edit', edit_plan_path(plan) %></td>
        <td><%= link_to 'Destroy', plan, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Plan', new_plan_path %>

app/views/plans/new.html.erb
<h1>New Plan</h1>

<%= render 'form', plan: @plan %>

<%= link_to 'Back', plans_path %>

app/views/plans/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @plan.name %>
</p>

<p>
  <strong>Amount:</strong>
  <%= @plan.amount %>
</p>

<p>
  <strong>Interval:</strong>
  <%= @plan.interval %>
</p>

<p>
  <strong>Desired plan:</strong>
  <%= @plan.desired_plan_id %>
</p>

<p>
  <strong>Stripe plan:</strong>
  <%= @plan.stripe_plan_id %>
</p>

<%= link_to 'Edit', edit_plan_path(@plan) %> |
<%= link_to 'Back', plans_path %>